### ISSUE TITLE
Code for test?

### ISSUE THREAD

**Issue by TiankangXie** [ClaudiaShu/SSL-FER#1]
Hi,

I am wondering where I could find a script for testing the pre-trained model performances on AffectNet/FER/new dataset?

Thank you so much for sharing code!

**Comment by ClaudiaShu** [comment]
Hi, sorry for this late response. Please find the code for testing on AffectNet here: https://github.com/ClaudiaShu/EMO_AffectNet
I will update the link to this repo. 

Hope this is helpful!
