### ISSUE TITLE
How to use pretrained on FER2013, dataset structure?

### ISSUE THREAD

**Issue by saifhassan** [ClaudiaShu/SSL-FER#2]
Hey @ClaudiaShu 

Thank you for this great contribution.

Can you please guide, How pre-trained model can be used on FER2013/AffectNet dataset. Guide dataset structure for AffectNet/FER2013 please and what changes possibly I will have to do.

Thanks in advance.

**Comment by ClaudiaShu** [comment]
Hi @saifhassan ! Thank you for acknowledging our work!

For model evaluation, we followed [usef-kh/fer](https://github.com/usef-kh/fer). You may find the details there. The evaluation of Affectnet and LFW can be found here: [ClaudiaShu/EMO_AffectNet](https://github.com/ClaudiaShu/EMO_AffectNet).

Hope this is helpful!
