### ISSUE TITLE
Requesting for "vox1_frames_test.txt"

### ISSUE THREAD

**Issue by 25ankitadas** [ClaudiaShu/SSL-FER#3]
I cannot find "vox1_frames_test.txt" file. Can you please provide me that file or information how to get that file?  Thanks in advance.

**Comment by ClaudiaShu** [comment]
Hi @25ankitadas,

"vox1_frames.txt" is a file that contains the frame information of each training instance in the vox1 dataset. I have uploaded the file under the folder `dataset`. You may use that to run on the full vox1 dataset.

"vox1_frames_test.txt" is a subset of "vox1_frames.txt" that I sampled from the full file. You may also run a quick test on our code by using only partial frames.

Hope this is helpful!

**Comment by 25ankitadas** [comment]
Thanks alot

**Comment by 25ankitadas** [comment]
could you please tell me where to get the voxceleb1 dataset that is used in self.prefix_vox1 = 'pathto/VoxCeleb/vox1'  in data_aug/data_loader.py? Thanks in advance.

**Comment by ClaudiaShu** [comment]
Hi, the link to the dataset is - https://mm.kaist.ac.kr/datasets/voxceleb/. This can be found in the readme.md file.

The authors of the voxceleb1 dataset might have updated the access to the dataset. Please email them for more details and access to the full vox1 dataset as we are not the owner of the dataset. They have provided their email on their official website.
